/** Real local GoTrue/JWT, PostgREST/RLS and Realtime. No hosted credentials. */
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { joinPath } from '../lib/join-path.ts';
const config = JSON.parse(execFileSync('supabase', ['status', '-o', 'json'], { cwd: '..', encoding: 'utf8', stdio: ['ignore','pipe','pipe'] }));
const url = config.API_URL, key = config.ANON_KEY;
assert.ok(/^http:\/\/(127\.0\.0\.1|localhost):54321$/.test(url), 'Only the disposable local stack is allowed');
const clients = Array.from({ length: 3 }, () => createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }));
const [owner, guest, outsider] = clients;
const ok = async (operation) => { const r = await operation; assert.equal(r.error, null, r.error?.message); return r.data; };
const denied = async (operation) => { const r = await operation; assert.ok(r.error, 'Unauthorized write must fail'); };
const deadline = async (promise, label) => { let timer; try { return await Promise.race([promise, new Promise((_, reject) => { timer = setTimeout(() => reject(Error(label + ' timed out')), 20000); })]); } finally { clearTimeout(timer); } };
const channels=[];
async function subscription(client, room, onMessage) {
  const channel=client.channel(`wyd-room-${room}`, {config:{ private:true, presence:{ key:randomUUID() } }});
  channels.push([client,channel]);
  channel.on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room_id=eq.${room}`},onMessage);
  await deadline(new Promise((resolve,reject)=>channel.subscribe(status=>{
    if(status==='SUBSCRIBED')resolve();
    if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')reject(Error(status));
  })), 'Realtime subscription');
  return channel;
}
try {
  const auth = await Promise.all(clients.map(client=>ok(client.auth.signInAnonymously())));
  assert.ok(auth.every(result=>result.user?.is_anonymous && result.session?.access_token));
  const [ownerId,guestId]=auth.map(result=>result.user.id);
  assert.notEqual(ownerId,guestId);
  for(const client of clients) assert.ok((await ok(client.auth.getUser())).user.id);
  console.log('PASS: Three independent anonymous sessions verified by GoTrue');
  const event = await ok(owner.rpc('create_wyd_event',{p_name:'WYD CI event',p_description:'Synthetic participants only',p_start_at:null,p_end_at:null,p_display_name:'Host test',p_language:'ko'}));
  assert.match(event,/^[0-9a-f]{32}$/);
  const invitation=joinPath(`https://event.example/event/${event}`);
  assert.equal(invitation,`/event/${event}`);
  const rooms=await ok(owner.from('rooms').select('*').eq('event_id',event));
  const room=rooms[0].id;
  assert.equal((await ok(outsider.from('events').select('*').eq('id',event))).length,0);
  await denied(outsider.rpc('end_wyd_event',{p_event_id:event,p_user_id:ownerId}));
  await ok(guest.rpc('join_wyd_event',{p_event_id:invitation.split('/').pop(),p_display_name:'Guest test',p_language:'fr'}));
  await Promise.all([[owner,'Host test','ko'],[guest,'Guest test','fr']].map(([client,name,language])=>ok(client.rpc('join_wyd_room',{p_room_id:room,p_display_name:name,p_language:language}))));
  console.log('PASS: QR invitation joins a second language; outsiders cannot read or end the event');
  let receive;
  const received=new Promise(resolve=>{receive=resolve;});
  let channel=await subscription(guest,room,payload=>receive(payload.new));
  const request={p_room_id:room,p_client_message_id:randomUUID(),p_content:'Meet at the main gate.',p_source_language:'en'};
  const [first,second]=await Promise.all([ok(owner.rpc('send_wyd_message',request).single()),ok(owner.rpc('send_wyd_message',request).single())]);
  assert.equal(first.id,second.id);
  assert.equal((await deadline(received,'Realtime message')).id,first.id);
  assert.equal((await ok(guest.from('messages').select('*').eq('room_id',room))).length,1);
  await denied(guest.from('messages').update({content:'forged edit'}).eq('id',first.id));
  await denied(guest.from('messages').insert({room_id:room,sender_id:ownerId,client_message_id:randomUUID(),content:'spoof',source_language:'en'}));
  const fake=await fetch(`${url}/rest/v1/events`,{headers:{apikey:key,Authorization:`Bearer ${ownerId}`}});
  assert.equal(fake.status,401);
  console.log('PASS: Live message delivery, duplicate suppression and forged user/message rejection');
  await guest.removeChannel(channel);
  await ok(owner.rpc('send_wyd_message',{...request,p_client_message_id:randomUUID(),p_content:'Sent during disconnect.'}));
  channel=await subscription(guest,room,()=>{});
  const recovered=await ok(guest.from('messages').select('*').eq('room_id',room).order('created_at'));
  assert.equal(recovered.length,2);
  console.log('PASS: After Realtime reconnect, database refresh recovers the missed message');
  await denied(guest.from('event_announcements').insert({event_id:event,author_id:guestId,content:'unauthorized',source_language:'fr',priority:'urgent'}));
  const announcement=await ok(owner.from('event_announcements').insert({event_id:event,author_id:ownerId,content:'Urgent test: meet at gate.',source_language:'en',priority:'urgent'}).select().single());
  await ok(guest.from('event_announcement_reads').insert({event_id:event,announcement_id:announcement.id,user_id:guestId}));
  let receipt=await ok(owner.from('event_announcement_reads').select('*').eq('announcement_id',announcement.id).eq('user_id',guestId).single());
  assert.equal(receipt.acknowledged_at,null,'Reading is separate from explicit acknowledgement');
  await ok(guest.rpc('acknowledge_wyd_announcement',{p_scope:'event',p_announcement_id:announcement.id}));
  receipt=await ok(owner.from('event_announcement_reads').select('*').eq('announcement_id',announcement.id).eq('user_id',guestId).single());
  assert.ok(receipt.acknowledged_at);
  await ok(guest.rpc('acknowledge_wyd_announcement',{p_scope:'event',p_announcement_id:announcement.id}));
  assert.equal((await ok(owner.from('event_announcement_reads').select('*').eq('announcement_id',announcement.id))).length,1);
  await ok(owner.from('event_schedule_items').insert({event_id:event,title:'Gathering',description:'Synthetic schedule',starts_at:new Date(Date.now()+3600000).toISOString(),location_name:'Gate A',source_language:'en'}));
  await ok(owner.from('event_meeting_points').insert({event_id:event,name:'Gate A',details:'Synthetic meeting point',map_url:'https://maps.google.com/?q=Seoul',source_language:'en'}));
  assert.equal((await ok(guest.from('event_schedule_items').select('*').eq('event_id',event))).length,1);
  assert.equal((await ok(guest.from('event_meeting_points').select('*').eq('event_id',event))).length,1);
  console.log('PASS: Urgent announcement, separate read/confirmed receipts, schedule and meeting place');
  await denied(guest.rpc('set_wyd_participant_role',{p_event_id:event,p_user_id:guestId,p_role:'staff'}));
  await ok(owner.rpc('set_wyd_participant_role',{p_event_id:event,p_user_id:guestId,p_role:'staff'}));
  await ok(guest.rpc('join_wyd_event',{p_event_id:event,p_display_name:'Guest test',p_language:'fr'}));
  assert.equal((await ok(guest.from('event_participants').select('role').eq('event_id',event).eq('user_id',guestId).single())).role,'staff');
  await ok(guest.from('event_announcements').insert({event_id:event,author_id:guestId,content:'Staff notice',source_language:'fr',priority:'important'}));
  await denied(guest.rpc('end_wyd_event',{p_event_id:event}));
  await ok(owner.rpc('reserve_wyd_translation',{p_characters:4999}));
  await denied(guest.rpc('reserve_wyd_translation',{p_characters:2}));
  await ok(guest.rpc('reserve_wyd_translation',{p_characters:1}));
  console.log('PASS: Organizer/staff separation and shared translation allowance across users');
  await ok(owner.rpc('end_wyd_event',{p_event_id:event}));
  assert.ok((await ok(guest.from('rooms').select('status').eq('event_id',event))).every(r=>r.status==='ended'));
  await denied(guest.rpc('send_wyd_message',{...request,p_client_message_id:randomUUID(),p_content:'After closure'}));
  await denied(outsider.rpc('join_wyd_event',{p_event_id:event,p_display_name:'Late guest',p_language:'es'}));
  assert.equal((await ok(guest.from('messages').select('*').eq('room_id',room))).length,2);
  console.log('PASS: Atomic event closure, no new joins or messages, existing history preserved');
} finally {
  await Promise.allSettled(channels.map(([client,channel])=>client.removeChannel(channel)));
  for(const client of clients) await client.removeAllChannels();
}
